project_id = "ywnmxrpasfikvwdgexdo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.monitor-signals]
verify_jwt = false

[functions.get-live-prices]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.subscribe-push]
verify_jwt = false
